name: AutoMessage
version: ${project.version}
authors: [ELCHILEN0, Kismalax]
description: Schedule easily configurable broadcasts!
website: http://www.novuscraft.org
main: com.teamnovus.automessage.AutoMessage
api-version: 1.17
commands:
   automessage:
     description: Main command for all AutoMessage commands
     aliases: [automsg, am]